### ISSUE TITLE
volumio modules for 4.14.26

### ISSUE THREAD

**Issue by macmpi** [taudac/modules#1]
Hi,
as @volumio is making test builds with most recent 4.14 branch, can you please provide relevant modules?
I guess dkms build now works fine under 4.14, right?

**Comment by howardqiao** [comment]
missed taudac 4.14.26 support(RPI 3B+ Support) when building volumio,

**Comment by howardqiao** [comment]
Please do not affect the Volumio release of a new version of the support for RPI3B+

**Comment by macmpi** [comment]
Thanks.
